default_platform(:ios)

platform :ios do
  desc "Build IPA"
  lane :build do
    gym(
      scheme: "ChargingAwake",
      export_method: "ad-hoc",
      output_name: "ChargingAwake",
      include_bitcode: false,
      include_symbols: true
    )
  end
end
